export const RADIX_HUES = [
  "amber",
  "blue",
  "bronze",
  "brown",
  "crimson",
  "cyan",
  "gold",
  "grass",
  "gray",
  "green",
  "indigo",
  "lime",
  "mauve",
  "mint",
  "olive",
  "orange",
  "pink",
  "plum",
  "purple",
  "red",
  "sage",
  "sand",
  "sky",
  "slate",
  "teal",
  "tomato",
  "violet",
  "yellow",
  "jade",
  "iris",
  "ruby",
] as const;

export const ALPHAS = ["", "A"] as const;
export const P3S = ["", "P3"] as const;
export const STEPS = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "-fg"] as const;
